---
title: "🗓️ Semana 01: Introducción al curso"
---

En esta primera semana revisaremos los objetivos, evaluaciones y la estructura de trabajo del semestre. Luego, introduciremos el rol de la estadística dentro del proceso de investigación social empírica: cómo se relaciona con la teoría, qué supuestos implica la cuantificación de la realidad social y cómo ha sido usada en la sociología clásica y contemporánea.

## 👨‍🏫 Clase Expositiva

Puedes navegar por las diapositivas directamente en el recuadro de abajo o hacer clic [aquí](slides.qmd) para ver la presentación en pantalla completa. Usa las flechas de tu teclado para avanzar.

<div class="container" style="position: relative;overflow: hidden;width: 100%;min-height:600px;">
<iframe src="slides.html" style="position: absolute;top: 0;left: 0;bottom: 0;right: 0;width: 100%;min-height:600px;"></iframe>
</div>

## 📚 Lecturas Obligatorias

- **Babbie, E. (2000).** *Fundamentos de la investigación social*. Cengage Learning Latin Am. Caps. 1 y 2. [[PDF]](../../bib/Fundamentos De La Investigacion Social (Scan) (Babbie Earl)-1-72.pdf)
- **Cea D'Ancona, M. Á. (1996).** *Metodología cuantitativa: estrategias y técnicas de investigación social*. Síntesis. Cap. 2, págs. 81–120. [[PDF]](../../bib/Cea D'Ancona M. (1996) Metodología Cuantitativa-77-118.pdf)

## 📟 Dudas y Comunicación

Recuerda que puedes utilizar los canales de comunicación establecidos o acercarte al profesor y ayudantes si tienes dudas sobre los contenidos de esta semana.
